name: virtual_learning
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  go_router:
  sqflite:
  path_provider:
  shared_preferences:
  hive:
  cached_network_image: ^3.3.1
  photo_view:
  image_picker:
  flutter_chat_ui:
  flutter_markdown_plus:
  lottie:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  package_config: ^2.2.0
  firebase_storage: ^12.4.10
  diffutil_dart: ^4.0.1
  http: ^0.13.6
  
  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter: { assets: [ assets/images/microscope.png, assets/images/slides/,
                     assets/data/slides.json, assets/data/quizzes.json,
                     assets/data/hotspots.json, assets/data/annotations.json ], uses-material-design: true,
           shaders: [    ], fonts: [    ], generate: false }
